export const TRANSLATIONS = {
  hello: 'hello',
  home: 'Home',
  loginTitle: 'Login',
  username: 'Username',
  password: 'Password',
  login: 'Login',
  incorrectLogin: 'username or password is incorrect',
  profile: 'Profile',
  logout: 'Logout',
  users: 'Users',
  food: 'Food',
  firstName: 'First Name',
  lastName: 'Last Name',
  isAdmin: 'Is Admin',
  name: 'Name',
  date: 'Date',
  price: 'Price',
  calorie: 'Calorie',
  user: 'User',
  update: 'Update',
  create: 'Create',
  caloriePerDay: 'Calories Per Day',
  budgetPerMonth: 'Budget Per Month',
  search: 'Search',
  createdByAdmin: 'Created By Admin',
  createWith: (name: string) => `Create ${name}`,
  updateWith: (name: string) => `Update ${name}`,
  viewWith: (name: string) => `View ${name}`,
  dateFrom: 'Date From',
  dateTo: 'Date To',

  totalCalories: 'Total Calories',
  totalPrice: 'Total Price',
  averageCalories: 'Average Calories',
  averagePrice: 'Average Price',
  monthly: 'Monthly',
  month: 'Month',
  totalCount: 'Count',
  totalPriceOnMonth: 'Total price on month',
  exceed: 'Exceed',
  foodStats: 'Food Statistics',
  userStatisticsSelectedWeek: 'User Statistics For Selected Week',
  currentWeek: 'Current Week',
  previousWeek: 'Previous Week',
  weekStats: 'Week Statistics',
  weekStatsChart: 'Week Statistics Chart',
  loadingChart: 'Loading Weeks chart'
}
