export * from './IUser'
export * from './IFood'
export * from './ILogin'
export * from './IAuthorizedDto'
export * from './IProjectVariables';
export * from './IEnvironment';
export * from './Modes';
export * from './IFoodFilter';
export * from './IGroupedFood';
export * from './IStats';
export * from './IGroupResponse';
